<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HTPC" name="testNG.loginLogoutDataDriveTesintUsingTestNG" tests="13" failures="2" timestamp="05 Nov 2018 00:34:48 GMT" time="93.386" errors="0">
  <testcase name="loginLogoutTestWithCorrectCredencials" time="6.908" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWithCorrectCredencials" time="8.988" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWtihIncorrectCredencials" time="6.342" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWtihIncorrectCredencials" time="5.939" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWithCorrectCredencials" time="8.933" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWtihIncorrectCredencials" time="6.322" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWithCorrectCredencials" time="6.316" classname="testNG.loginLogoutDataDriveTesintUsingTestNG">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at testNG.loginLogoutDataDriveTesintUsingTestNG.loginLogoutTestWithCorrectCredencials(loginLogoutDataDriveTesintUsingTestNG.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginLogoutTestWithCorrectCredencials -->
  <testcase name="loginLogoutTestWithCorrectCredencials" time="11.722" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWtihIncorrectCredencials" time="6.394" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWithCorrectCredencials" time="6.290" classname="testNG.loginLogoutDataDriveTesintUsingTestNG">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at testNG.loginLogoutDataDriveTesintUsingTestNG.loginLogoutTestWithCorrectCredencials(loginLogoutDataDriveTesintUsingTestNG.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginLogoutTestWithCorrectCredencials -->
  <testcase name="loginLogoutTestWtihIncorrectCredencials" time="6.414" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWtihIncorrectCredencials" time="6.395" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
  <testcase name="loginLogoutTestWtihIncorrectCredencials" time="6.423" classname="testNG.loginLogoutDataDriveTesintUsingTestNG"/>
</testsuite> <!-- testNG.loginLogoutDataDriveTesintUsingTestNG -->
